### ISSUE TITLE
Incompatible with NumPy 1.22

### ISSUE THREAD

**Issue by FrancisTong** [scatseisnet/scatseisnet#1]
NumPy 1.22 introduces breaking changes to Obspy, which is a Scatseisnet dependency. Therefore at this time, Scatseisnet will only work with NumPy 1.21.5 or older.

**Comment by leonard-seydoux** [comment]
A year later: the bug was corrected by ObsPy. And ObsPy is not anymore fully needed by Scatseisnet, so we will not experience this type of bug later on. Closing the issue.
