### ISSUE TITLE
network.transform_segment returns unexpected shape

### ISSUE THREAD

**Issue by tbartholomaus** [scatseisnet/scatseisnet#21]
In the [example use of `network.transform_segment`](https://github.com/scatseisnet/scatseisnet/blob/main/scatseisnet/network.py#L135), the shape of the second layer of scattering coefficients is [expected to be (64, 24)](https://github.com/scatseisnet/scatseisnet/blob/main/scatseisnet/network.py#L151), but when I run the same example code (modified slightly, [according to this PR](https://github.com/scatseisnet/scatseisnet/pull/20)), I get (64,12).  Is this a problem?

Code:
```python
import numpy as np
from scatseisnet import ScatteringNetwork

layer_kwargs = [
    {"octaves": 8, "resolution": 8},
    {"octaves": 12, "resolution": 1},
]
network = ScatteringNetwork(*layer_kwargs)

segment = np.random.randn(128)

scattering_coefficients = network.transform_segment(segment, reduce_type=np.max)
print( len(scattering_coefficients) )
print( scattering_coefficients[0].shape )
print( scattering_coefficients[1].shape )
```

Output:
```
2
(64,)
(64, 12)
```

Many thanks

**Comment by Lchuang** [comment]
I am guessing the 24 in the (64, 24) of the example is a typo since each layer's total number of filters is the number of octaves x the number of resolutions. 

Since the second layer has "octaves": 12, "resolution": 1, the expected shape of scattering_coefficients should be 12?

**Comment by tbartholomaus** [comment]
Thanks Leonard.  However, I was still curious about the size [(64, 24)](https://github.com/scatseisnet/scatseisnet/blob/91226eea023de55e3ac91585be567da778caaf50/scatseisnet/network.py#L157), in the example/comment for the function transform_segment.  I hadn't actually resolved this in my PR.

Can you confirm as per @Lchuang's [comment above](https://github.com/scatseisnet/scatseisnet/issues/21#issuecomment-1491194614) that this was a typo, and should be corrected to actually be a size of (64, 12)?
