### ISSUE TITLE
stream.slide producing segments of different length

### ISSUE THREAD

**Issue by Lchuang** [scatseisnet/scatseisnet#22]
I think this is more of an obspy issue, but I thought I'd share in case someone else also runs into the same issue.

Ocassionally while using stream.slide to create segments, a few segments would end up having slightly different numbers of samples compared to other segments. And when that happens, it raises the broadcast errors shown below.

In my own test file, each segment should have 2000 points, but a few segments only have 1999 points. Those segments are not at the end of the files, which is a bit odd.

At first, I thought it was caused by gaps in the data, but the problem still existed after stream.merge() was applied.

Right now, my workaround is first to identify the short segments and then pad zeros to the end of them so they all become 2000 points long. Does anyone else also see the same problem? I would appreciate feedback on whether zero padding makes sense. Thank you!

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[45], line 1
----> 1 scattering_coefficients = network.transform(segments, reduce_type=np.max)

File ~/opt/anaconda3/envs/scattering/lib/python3.9/site-packages/scatseisnet/network.py:222, in ScatteringNetwork.transform(self, segments, reduce_type)
    220 # Calculate coefficients
    221 for segment in segments:
--> 222     scatterings = self.transform_segment(segment, reduce_type)
    223     for layer_index, scattering in enumerate(scatterings):
    224         features[layer_index].append(scattering)

File ~/opt/anaconda3/envs/scattering/lib/python3.9/site-packages/scatseisnet/network.py:160, in ScatteringNetwork.transform_segment(self, segment, reduce_type)
    156 # Calculate coefficients
    157 for bank in self.banks:
    158 
    159     # Get scalogram
--> 160     scalogram = bank.transform(segment)
    162     # Replace input segment by scalogram for the next layer
    163     segment = scalogram

File ~/opt/anaconda3/envs/scattering/lib/python3.9/site-packages/scatseisnet/wavelet.py:208, in ComplexMorletBank.transform(self, segment)
    191 def transform(self, segment: xp.ndarray) -> np.ndarray:
    192     """Compute the scalogram for a given segment.
    193 
    194     Parameters
   (...)
    206         `n_channels, ..., n_filters, n_bins`.
    207     """
--> 208     segment = xp.fft.fft(xp.array(segment) * xp.array(self.taper))
    209     convolved = segment[..., None, :] * xp.array(self.spectra)
    210     scalogram = xp.fft.fftshift(xp.fft.ifft(convolved), axes=-1)

ValueError: operands could not be broadcast together with shapes (3,1999) (2000,) 

```

**Comment by leonard-seydoux** [comment]
Agreed, this is more an ObsPy issue. Did you try to play around with the `include_partial_windows` keyword argument of the slide method? In any case, I always pad to the expected number of points (e.g., the sampling rate times the fixed duration) in order to prevent this from happening. Let us know if it helps.

**Comment by Lchuang** [comment]
Hi @leonard-seydoux, thank you for the suggestion! I played with the `include_partial_windows` keyword and recovered some even shorter signals. I dropped the ones that are too short (e.g. less than 80% of the target length), and then manually padded them to the target length. In general, padding doesn't take too much time so it is probably not a big issue. Thanks again. :)
