### ISSUE TITLE
Notebook 5_clustering description 

### ISSUE THREAD

**Issue by Lchuang** [scatseisnet/scatseisnet#25]
In tutorial notebook **5_clustering**
- Get cluster coordinates in the feature space, it says
> We here see that **cluster 4** is moslty constrained by **the feature 6**. 

However, based on the plot, it seems like cluster 4 is mostly constrained by the features 1 or 3,
And feature 4 seems to mostly constrain cluster 6. Was the order in the text reversed?
Thank you. :)

![matrix](https://user-images.githubusercontent.com/5347181/232184884-563ba942-8b72-4029-b1d8-fbfe2b6c5b12.png)

**Comment by Lchuang** [comment]
Ahh, I see; I must have left out the random state keyword during copy-pasting.
I am getting the same results while setting the random_state to 4.
I should have had a closer look before reporting the issue. Sorry about the trouble. 
Many thanks for the explanation!!

**Comment by Lchuang** [comment]
After running the series of notebooks a few times, I think it actually may be due to the `random_state` not being set in the FastICA in notebook 3_reduction.ipynb
> Extract independant features
`model = FastICA(n_components=10, whiten="unit-variance")`

Once I set the random_state to a fixed value, the results became consistent.
Thank you fro the hint of the `random_state` for k-means! :D

**Comment by leonard-seydoux** [comment]
Thanks for pointing this bug! We did not notice that `random_state` was missing from the dimensionality reduction notebook. This should work better now indeed. Note that I changed the display of feature contribution into cluster, by taking the absolute value of the centroid. It exhibits better the "absolute" contribution.
